import type { HopDong } from '../types';

// ⚠️ DỮ LIỆU DEMO — KHÔNG dùng trong luồng chạy thật.
// Trước đây mảng này được nối thẳng vào kết quả fetchHopDong() nên dữ liệu giả lẫn với
// dữ liệu thật và mọi chỉnh sửa chỉ nằm trong RAM (mất khi tải lại trang). Đã tách ra đây.
// LƯU Ý SAI ĐƠN VỊ: giaTri/daThanhToan trong app tính bằng TRIỆU ĐỒNG, nhưng dữ liệu dưới
// đây ghi theo ĐỒNG (vd 2500000 hiển thị thành "2.500 tỷ"). Cần chia 1.000.000 trước khi seed.
export const SAMPLE_20_HOP_DONG = [
  {
    id: 'hd-sample-1',
    soHD: 'HD-2026/001-KC',
    ten: 'Thử nghiệm chịu tải kết cấu cầu đường bộ cao tốc Bắc - Nam',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Viện chuyên ngành Kết cấu công trình',
    donViId: '1',
    giaTri: 2500000,
    daThanhToan: 0,
    ngayKy: '2026-01-10',
    hanHoanThanh: '2026-06-30',
    trangThai: 'moi',
    nhomHD: 'N1A',
    chuTriId: '1',
    chuTri: 'Nguyễn Minh Tuấn',
    giaDuThau: 2500000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'chua-trinh',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'du-thao',
  },
  {
    id: 'hd-sample-2',
    soHD: 'HD-2026/002-DKT',
    ten: 'Khảo sát địa kỹ thuật và quan trắc lún dự án Trung tâm Vũ trụ Việt Nam',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Viện chuyên ngành Địa kỹ thuật',
    donViId: '2',
    giaTri: 3200000,
    daThanhToan: 0,
    ngayKy: '2026-01-15',
    hanHoanThanh: '2026-08-15',
    trangThai: 'cho-duyet',
    nhomHD: 'N1A',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 3200000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'da-trinh',
    ngayTrinhDuyet: '2026-01-16',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'cho-duyet',
  },
  {
    id: 'hd-sample-3',
    soHD: 'HD-2026/003-BT',
    ten: 'Nghiên cứu cấp phối bê tông sỏi nhẹ cường độ cao cho công trình ven biển',
    khachHang: 'Tập đoàn Vingroup - CTCP',
    khachHangId: '2',
    donViThucHien: 'Viện chuyên ngành Bê tông',
    donViId: '3',
    giaTri: 1800000,
    daThanhToan: 0,
    ngayKy: '2026-01-20',
    hanHoanThanh: '2026-07-20',
    trangThai: 'cho-duyet',
    nhomHD: 'N1A',
    chuTriId: '3',
    chuTri: 'Lê Thị Mai',
    giaDuThau: 1800000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'chua-trinh',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'cho-duyet',
  },
  {
    id: 'hd-sample-4',
    soHD: 'HD-2026/004-BIM',
    ten: 'Tư vấn quy trình và xây dựng mô hình BIM 5D Cảng hàng không Quốc tế Long Thành',
    khachHang: 'Ban QLDA Đường sắt - Bộ Giao thông Vận tải',
    khachHangId: '4',
    donViThucHien: 'Trung tâm Tư vấn và Ứng dụng BIM',
    donViId: '4',
    giaTri: 6500000,
    daThanhToan: 0,
    ngayKy: '2026-01-25',
    hanHoanThanh: '2026-12-31',
    trangThai: 'cho-duyet',
    nhomHD: 'N2',
    chuTriId: '1',
    chuTri: 'Nguyễn Hồng Hải',
    giaDuThau: 6500000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'da-trinh',
    ngayTrinhDuyet: '2026-01-26',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'cho-duyet',
  },
  {
    id: 'hd-sample-5',
    soHD: 'HD-2026/005-KC',
    ten: 'Kiểm định chất lượng và gia cường kết cấu Tòa nhà Trụ sở Bộ Xây dựng',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Viện chuyên ngành Kết cấu công trình',
    donViId: '1',
    giaTri: 4200000,
    daThanhToan: 1500000,
    ngayKy: '2026-02-01',
    hanHoanThanh: '2026-09-30',
    trangThai: 'dang-thuc-hien',
    nhomHD: 'N2',
    chuTriId: '1',
    chuTri: 'Nguyễn Minh Tuấn',
    giaDuThau: 4200000,
    ngayNopHoSo: '2026-02-10',
    trangThaiPheDuyet: 'da-duyet',
    ngayTrinhDuyet: '2026-02-02',
    ngayDuyet: '2026-02-05',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'dang-thuc-hien',
  },
  {
    id: 'hd-sample-6',
    soHD: 'HD-2026/006-MN',
    ten: 'Khảo sát địa chất và thử nghiệm cọc dự án Tuyến Metro số 2 TP.HCM',
    khachHang: 'Tổng Công ty Đầu tư Phát triển Đường cao tốc Việt Nam (VEC)',
    khachHangId: '3',
    donViThucHien: 'Phân Viện KHCN Xây dựng miền Nam',
    donViId: '5',
    giaTri: 12000000,
    daThanhToan: 4000000,
    ngayKy: '2026-02-05',
    hanHoanThanh: '2026-11-30',
    trangThai: 'dang-thuc-hien',
    nhomHD: 'N3',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 12000000,
    ngayNopHoSo: '2026-02-15',
    trangThaiPheDuyet: 'da-duyet',
    ngayTrinhDuyet: '2026-02-06',
    ngayDuyet: '2026-02-08',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: true,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'dang-thuc-hien',
  },
  {
    id: 'hd-sample-7',
    soHD: 'HD-2026/007-DKT',
    ten: 'Quan trắc địa kỹ thuật móng sâu dự án Tháp Tài chính 88 tầng',
    khachHang: 'Công ty Cổ phần Tập đoàn Hòa Phát',
    khachHangId: '5',
    donViThucHien: 'Viện chuyên ngành Địa kỹ thuật',
    donViId: '2',
    giaTri: 2100000,
    daThanhToan: 1000000,
    ngayKy: '2026-02-10',
    hanHoanThanh: '2026-10-15',
    trangThai: 'dang-thuc-hien',
    nhomHD: 'N1A',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 2100000,
    ngayNopHoSo: '2026-02-20',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'dang-thuc-hien',
  },
  {
    id: 'hd-sample-8',
    soHD: 'HD-2026/008-BT',
    ten: 'Thử nghiệm độ bền ăn mòn bê tông cốt thép trong môi trường biển Phú Quốc',
    khachHang: 'Tập đoàn Vingroup - CTCP',
    khachHangId: '2',
    donViThucHien: 'Viện chuyên ngành Bê tông',
    donViId: '3',
    giaTri: 850000,
    daThanhToan: 200000,
    ngayKy: '2026-02-12',
    hanHoanThanh: '2026-06-15',
    trangThai: 'tam-dung',
    nhomHD: 'N2',
    chuTriId: '3',
    chuTri: 'Lê Thị Mai',
    giaDuThau: 850000,
    ngayNopHoSo: '2026-02-25',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'tam-dung',
  },
  {
    id: 'hd-sample-9',
    soHD: 'HD-2026/009-KC',
    ten: 'Thẩm tra thiết kế bản vẽ thi công và dự toán Nhà ga T3 Tân Sơn Nhất',
    khachHang: 'Ban QLDA Đường sắt - Bộ Giao thông Vận tải',
    khachHangId: '4',
    donViThucHien: 'Viện chuyên ngành Kết cấu công trình',
    donViId: '1',
    giaTri: 3800000,
    daThanhToan: 2500000,
    ngayKy: '2026-02-15',
    hanHoanThanh: '2026-07-31',
    trangThai: 'nghiem-thu',
    nhomHD: 'N2',
    chuTriId: '1',
    chuTri: 'Nguyễn Minh Tuấn',
    giaDuThau: 3800000,
    ngayNopHoSo: '2026-02-28',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'nghiem-thu',
  },
  {
    id: 'hd-sample-10',
    soHD: 'HD-2026/010-MT',
    ten: 'Thí nghiệm chỉ tiêu cơ lý đất đá phục vụ Cao tốc Cam Lộ - La Sơn',
    khachHang: 'Tổng Công ty Đầu tư Phát triển Đường cao tốc Việt Nam (VEC)',
    khachHangId: '3',
    donViThucHien: 'Phân Viện KHCN Xây dựng miền Trung',
    donViId: '6',
    giaTri: 1200000,
    daThanhToan: 800000,
    ngayKy: '2026-02-18',
    hanHoanThanh: '2026-05-30',
    trangThai: 'nghiem-thu',
    nhomHD: 'N1A',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 1200000,
    ngayNopHoSo: '2026-03-01',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: true,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'nghiem-thu',
  },
  {
    id: 'hd-sample-11',
    soHD: 'HD-2026/011-KHKT',
    ten: 'Biên soạn Tiêu chuẩn Quốc gia TCVN về Bê tông đầm lăn đập thủy điện',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Phòng Kế hoạch - Kỹ thuật',
    donViId: '7',
    giaTri: 1500000,
    daThanhToan: 1500000,
    ngayKy: '2026-01-05',
    hanHoanThanh: '2026-04-30',
    trangThai: 'quyet-toan',
    nhomHD: 'N1B',
    chuTriId: '1',
    chuTri: 'Trần Văn Hùng',
    giaDuThau: 1500000,
    ngayNopHoSo: '2026-01-15',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '2026-05-15',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'quyet-toan',
  },
  {
    id: 'hd-sample-12',
    soHD: 'HD-2026/012-DKT',
    ten: 'Khảo sát gia cố mái taluy sạt lở Quốc lộ 6 khu vực Hòa Bình',
    khachHang: 'Tổng Công ty Đầu tư Phát triển Đường cao tốc Việt Nam (VEC)',
    khachHangId: '3',
    donViThucHien: 'Viện chuyên ngành Địa kỹ thuật',
    donViId: '2',
    giaTri: 950000,
    daThanhToan: 950000,
    ngayKy: '2026-01-08',
    hanHoanThanh: '2026-04-15',
    trangThai: 'quyet-toan',
    nhomHD: 'N1A',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 950000,
    ngayNopHoSo: '2026-01-20',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'quyet-toan',
  },
  {
    id: 'hd-sample-13',
    soHD: 'HD-2026/013-BT',
    ten: 'Thí nghiệm mỏi và xác định tuổi thọ kết cấu bê tông đúc sẵn',
    khachHang: 'Tập đoàn Vingroup - CTCP',
    khachHangId: '2',
    donViThucHien: 'Viện chuyên ngành Bê tông',
    donViId: '3',
    giaTri: 1400000,
    daThanhToan: 1400000,
    ngayKy: '2026-01-02',
    hanHoanThanh: '2026-03-31',
    trangThai: 'hoan-thanh',
    nhomHD: 'N2',
    chuTriId: '3',
    chuTri: 'Lê Thị Mai',
    giaDuThau: 1400000,
    ngayNopHoSo: '2026-01-10',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'da-quyet-toan',
    ngayQuyetToan: '2026-04-10',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'hoan-thanh',
  },
  {
    id: 'hd-sample-14',
    soHD: 'HD-2026/014-KC',
    ten: 'Tư vấn giám sát lắp dựng kết cấu thép Nhà máy Nhiệt điện Thái Bình 2',
    khachHang: 'Công ty Cổ phần Tập đoàn Hòa Phát',
    khachHangId: '5',
    donViThucHien: 'Viện chuyên ngành Kết cấu công trình',
    donViId: '1',
    giaTri: 8900000,
    daThanhToan: 8900000,
    ngayKy: '2025-11-01',
    hanHoanThanh: '2026-03-15',
    trangThai: 'hoan-thanh',
    nhomHD: 'N3',
    chuTriId: '1',
    chuTri: 'Nguyễn Minh Tuấn',
    giaDuThau: 8900000,
    ngayNopHoSo: '2025-11-10',
    trangThaiPheDuyet: 'da-duyet',
    ngayTrinhDuyet: '2025-11-02',
    ngayDuyet: '2025-11-05',
    trangThaiQuyetToan: 'da-quyet-toan',
    ngayQuyetToan: '2026-03-25',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'hoan-thanh',
  },
  {
    id: 'hd-sample-15',
    soHD: 'HD-2026/015-BIM',
    ten: 'Đào tạo và chuyển giao công nghệ BIM cho Tập đoàn Dầu khí Việt Nam',
    khachHang: 'Ban QLDA Đường sắt - Bộ Giao thông Vận tải',
    khachHangId: '4',
    donViThucHien: 'Trung tâm Tư vấn và Ứng dụng BIM',
    donViId: '4',
    giaTri: 750000,
    daThanhToan: 750000,
    ngayKy: '2025-10-15',
    hanHoanThanh: '2026-02-28',
    trangThai: 'thanh-ly',
    nhomHD: 'N2',
    chuTriId: '1',
    chuTri: 'Nguyễn Hồng Hải',
    giaDuThau: 750000,
    ngayNopHoSo: '2025-10-20',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'da-quyet-toan',
    ngayQuyetToan: '2026-03-05',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'thanh-ly',
  },
  {
    id: 'hd-sample-16',
    soHD: 'HD-2026/016-MN',
    ten: 'Kiểm định sự cố nghiêng lệch chung cư cũ Phường 12 Quận 5 TP.HCM',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Phân Viện KHCN Xây dựng miền Nam',
    donViId: '5',
    giaTri: 600000,
    daThanhToan: 600000,
    ngayKy: '2025-09-01',
    hanHoanThanh: '2026-01-31',
    trangThai: 'thanh-ly',
    nhomHD: 'N1A',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 600000,
    ngayNopHoSo: '2025-09-10',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'da-quyet-toan',
    ngayQuyetToan: '2026-02-15',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: true,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'thanh-ly',
  },
  {
    id: 'hd-sample-17',
    soHD: 'HD-2026/017-DKT',
    ten: 'Thử nghiệm hầm gió mô hình cầu dây văng Rạch Miễu 2',
    khachHang: 'Tổng Công ty Đầu tư Phát triển Đường cao tốc Việt Nam (VEC)',
    khachHangId: '3',
    donViThucHien: 'Viện chuyên ngành Địa kỹ thuật',
    donViId: '2',
    giaTri: 2900000,
    daThanhToan: 0,
    ngayKy: '2026-01-12',
    hanHoanThanh: '2026-06-30',
    trangThai: 'huy',
    nhomHD: 'N2',
    chuTriId: '2',
    chuTri: 'Phạm Hoàng Anh',
    giaDuThau: 2900000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'huy',
  },
  {
    id: 'hd-sample-18',
    soHD: 'HD-2026/018-KC',
    ten: 'Quan trắc biến dạng nhiệt kết cấu Đập thủy điện Sơn La',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Viện chuyên ngành Kết cấu công trình',
    donViId: '1',
    giaTri: 2200000,
    daThanhToan: 500000,
    ngayKy: '2026-02-20',
    hanHoanThanh: '2026-11-30',
    trangThai: 'dang-thuc-hien',
    nhomHD: 'N1B',
    chuTriId: '1',
    chuTri: 'Nguyễn Minh Tuấn',
    giaDuThau: 2200000,
    ngayNopHoSo: '2026-02-28',
    trangThaiPheDuyet: 'khong-ap-dung',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'dang-thuc-hien',
  },
  {
    id: 'hd-sample-19',
    soHD: 'HD-2026/019-BT',
    ten: 'Kiểm tra đánh giá chất lượng bê tông vỏ hầm đường bộ Đèo Cả',
    khachHang: 'Tổng Công ty Đầu tư Phát triển Đường cao tốc Việt Nam (VEC)',
    khachHangId: '3',
    donViThucHien: 'Viện chuyên ngành Bê tông',
    donViId: '3',
    giaTri: 2700000,
    daThanhToan: 0,
    ngayKy: '2026-02-22',
    hanHoanThanh: '2026-09-15',
    trangThai: 'cho-duyet',
    nhomHD: 'N1A',
    chuTriId: '3',
    chuTri: 'Lê Thị Mai',
    giaDuThau: 2700000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'da-trinh',
    ngayTrinhDuyet: '2026-02-23',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
    buocHienTai: 'cho-duyet',
  },
  {
    id: 'hd-sample-20',
    soHD: 'HD-2026/020-BIM',
    ten: 'Tư vấn quản lý dự án số hóa di sản và công trình văn hóa quốc gia',
    khachHang: 'Ban Quản lý Dự án Đầu tư Xây dựng Chuyên ngành Bộ Xây dựng',
    khachHangId: '1',
    donViThucHien: 'Trung tâm Tư vấn và Ứng dụng BIM',
    donViId: '4',
    giaTri: 1100000,
    daThanhToan: 0,
    ngayKy: '2026-02-25',
    hanHoanThanh: '2026-10-30',
    trangThai: 'moi',
    nhomHD: 'N2',
    chuTriId: '1',
    chuTri: 'Nguyễn Hồng Hải',
    giaDuThau: 1100000,
    ngayNopHoSo: '',
    trangThaiPheDuyet: 'chua-trinh',
    ngayTrinhDuyet: '',
    ngayDuyet: '',
    trangThaiQuyetToan: 'chua-quyet-toan',
    ngayQuyetToan: '',
    hanChungTuQuyetToan: '',
    loaiDacThu: null,
    phanVienXa: false,
    giamTheoYeuCauDonVi: false,
  },
] as HopDong[];
