/**
 * scripts/seed_data_units.cjs
 * 
 * Danh mục 80 hợp đồng mẫu cho 16 đơn vị chuyên môn & sản xuất của Viện IBST.
 * Mỗi đơn vị đúng 5 hợp đồng, trải đều 5 bước quy trình:
 *   - du-thao
 *   - cho-duyet
 *   - dang-thuc-hien
 *   - hoan-thanh
 *   - thanh-ly
 * 
 * Phù hợp với năng lực kỹ thuật và chức năng quy định của từng đơn vị.
 */

const contractsData = [
  // ==========================================
  // ĐƠN VỊ 1: IBST.KC - Viện chuyên ngành Kết cấu công trình xây dựng
  // ==========================================
  {
    unitId: 1,
    soHD: '101/2026/HDKS-VKC',
    ten: 'Khảo sát & Đánh giá an toàn chịu lực kết cấu nhà ga T2 Cảng HKQT Nội Bài',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    clientIdx: 0,
    giaTri: 5200,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-15',
    hanHoanThanh: '2026-08-15',
    noiDung: 'Thực hiện khảo sát chi tiết hiện trạng, siêu âm cốt thép, thí nghiệm nén mẫu bê tông và lập báo cáo đánh giá an toàn chịu lực tổng thể Nhà ga T2 Nội Bài.',
    hasJointVenture: true,
    jointVentureName: 'Tổng công ty Xây dựng LICOGI',
    jointVenturePct: 30,
  },
  {
    unitId: 1,
    soHD: '102/2026/HDTV-VKC',
    ten: 'Tư vấn thẩm tra thiết kế kỹ thuật & dự toán công trình Trung tâm Đổi mới sáng tạo NIC Hòa Lạc',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 1800,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-30',
    noiDung: 'Thẩm tra mô hình kết cấu 3D SAP2000/ETABS, kiểm tra khả năng chịu lực khung vách bê tông cốt thép toàn khối và khối lượng dự toán.',
    hasJointVenture: false,
  },
  {
    unitId: 1,
    soHD: '103/2026/HDGD-VKC',
    ten: 'Giám định sự cố nứt vách & lún lệch khối tháp hỗn hợp 35 tầng tại Bắc Ninh',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 2400,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-05-01',
    hanHoanThanh: '2026-09-01',
    noiDung: 'Giám định nguyên nhân nứt kết cấu, quan trắc lún nghiêng bằng thiết bị Leica TotalStation và đề xuất giải pháp xử lý gia cố móng.',
    hasJointVenture: false,
  },
  {
    unitId: 1,
    soHD: '104/2026/HDTN-VKC',
    ten: 'Thử nghiệm tải trọng tĩnh kết cấu dầm cầu vượt đường sắt đô thị Nhổn - Ga Hà Nội',
    nhomHD: 'N2B',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 3600,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-11-10',
    hanHoanThanh: '2026-05-10',
    noiDung: 'Gia tải thử tĩnh nhịp dầm chữ U bằng xe tải nặng chuyên dụng, đo độ võng đàn hồi và dao động riêng của dầm cầu.',
    hasJointVenture: false,
  },
  {
    unitId: 1,
    soHD: '105/2026/HDTV-VKC',
    ten: 'Tư vấn thiết kế biện pháp gia cường kháng chấn trụ sở cơ quan Trung ương',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 4200,
    phanTramChuTri: 78,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-08-15',
    hanHoanThanh: '2026-02-15',
    noiDung: 'Lập giải pháp thiết kế bổ sung khung giằng thép và hệ giảm chấn ma sát cao su nhằm tăng khả năng kháng chấn cấp VII cho công trình.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 2: IBST.BT - Viện chuyên ngành Bê tông
  // ==========================================
  {
    unitId: 2,
    soHD: '201/2026/HDTN-VBT',
    ten: 'Thí nghiệm kiểm định độ bền nhiệt & ăn mòn bê tông khối lớn Thủy điện Hòa Bình mở rộng',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    clientIdx: 6,
    giaTri: 3800,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-20',
    hanHoanThanh: '2026-07-20',
    noiDung: 'Thí nghiệm độ chống thấm nước, độ bền băng giá, ứng suất nhiệt bê tông khối lớn móng trạm biến áp và đập tràn.',
    hasJointVenture: false,
  },
  {
    unitId: 2,
    soHD: '202/2026/HDKS-VBT',
    ten: 'Nghiên cứu & Cung cấp phụ gia bê tông chịu nén cao cho tuyến hầm Metro Hà Nội',
    nhomHD: 'N2C',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 2900,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-10-30',
    noiDung: 'Thử nghiệm cấp phối bê tông siêu tính năng (UHPC), tối ưu hóa hàm lượng sợi thép và phụ gia siêu dẻo cho vỏ hầm.',
    hasJointVenture: false,
  },
  {
    unitId: 2,
    soHD: '203/2026/HDTN-VBT',
    ten: 'Thí nghiệm kiểm tra không phá hủy siêu âm khuyết tật cấu kiện bê tông đúc sẵn Cầu Nhật Tân',
    nhomHD: 'N2B',
    capKy: 'don-vi-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    clientIdx: 6,
    giaTri: 1600,
    phanTramChuTri: 85,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-10',
    hanHoanThanh: '2026-07-10',
    noiDung: 'Kiểm tra siêu âm vận tốc xung phát hiện rỗ khí và nứt ngầm trong các khối dầm hộp bê tông đúc sẵn khẩu độ lớn.',
    hasJointVenture: false,
  },
  {
    unitId: 2,
    soHD: '204/2026/HDTV-VBT',
    ten: 'Tư vấn công nghệ cấp phối bê tông tự lèn siêu tính năng UHPC cho dầm cầu vượt biển',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 4500,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-10-05',
    hanHoanThanh: '2026-04-05',
    noiDung: 'Thiết kế cấp phối và chuyển giao quy trình sản xuất bê tông tự lèn mác M800 chống xâm thực ion clorua tại hiện trường.',
    hasJointVenture: false,
  },
  {
    unitId: 2,
    soHD: '205/2026/HDTN-VBT',
    ten: 'Đánh giá độ bền băng giá & chống thấm áp lực cao đường hầm dẫn nước Sông Bung',
    nhomHD: 'N4',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 11,
    giaTri: 2100,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-07-12',
    hanHoanThanh: '2026-01-12',
    noiDung: 'Thí nghiệm chu kỳ đóng băng - tan băng 300 chu kỳ và đo hệ số thấm W12 đối với bê tông vỏ hầm chịu áp lực nước lớn.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 3: IBST.DKT - Viện chuyên ngành Địa kỹ thuật
  // ==========================================
  {
    unitId: 3,
    soHD: '301/2026/HDKS-VDKT',
    ten: 'Khảo sát địa kỹ thuật & Thí nghiệm nén hầm sâu tuyến cao tốc Bắc - Nam đoạn qua Quảng Trị',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    clientIdx: 2,
    giaTri: 7500,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-03-01',
    hanHoanThanh: '2026-11-01',
    noiDung: 'Khoan khảo sát địa chất công trình 35 lỗ khoan sâu 50m, thí nghiệm xuyên tĩnh CPT, cắt cánh vạn năng hiện trường và cắt nén 3 trục UU/CU.',
    hasJointVenture: true,
    jointVentureName: 'CTCP Khảo sát Địa chất Miền Trung',
    jointVenturePct: 35,
  },
  {
    unitId: 3,
    soHD: '302/2026/HDTC-VDKT',
    ten: 'Thi công xử lý nền đất yếu bằng cọc bêtông ly tâm D500 dự án Cảng sông Thuận An',
    nhomHD: 'N3',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 11,
    giaTri: 12500,
    phanTramChuTri: 90,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-11-10',
    hanHoanThanh: '2026-05-10',
    noiDung: 'Thi công ép cọc bê tông ly tâm ứng lực trước D500 mm, thử tĩnh cọc 400 tấn và nén tĩnh đất nền.',
    hasJointVenture: false,
  },
  {
    unitId: 3,
    soHD: '303/2026/HDKS-VDKT',
    ten: 'Khoan khảo sát địa chất & Thí nghiệm xuyên tĩnh CPTu mở rộng KCN Deep C Hải Phòng',
    nhomHD: 'N2E',
    capKy: 'don-vi-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    clientIdx: 1,
    giaTri: 2200,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-08-30',
    noiDung: 'Khoan lấy mẫu đất nguyên dạng tầng bùn sét yếu, đo áp lực nước lỗ rỗng CPTu và thí nghiệm nén cố kết Odomet.',
    hasJointVenture: false,
  },
  {
    unitId: 3,
    soHD: '304/2026/HDTV-VDKT',
    ten: 'Tư vấn thiết kế hệ văng chống tường vây hố đào sâu 4 tầng hầm dự án VietinBank Tower',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 3,
    giaTri: 3400,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-15',
    hanHoanThanh: '2026-08-15',
    noiDung: 'Mô phỏng phần tử hữu hạn PLAXIS 3D phân tích chuyển vị tường vây, tính toán neo đất dự ứng lực và hệ thanh chống kingpost.',
    hasJointVenture: false,
  },
  {
    unitId: 3,
    soHD: '305/2026/HDGD-VDKT',
    ten: 'Quan trắc biến dạng hố đào & Giám định sạt trượt bờ dốc đường ven biển Quảng Ninh',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 2800,
    phanTramChuTri: 78,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-09-01',
    hanHoanThanh: '2026-03-01',
    noiDung: 'Đo chuyển vị ngang bằng ống Inclinometer, quan trắc mực nước ngầm Piezometer và lập báo cáo nguyên nhân sạt trượt cơ taluy.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 4: IBST.MN - Phân Viện KHCN Xây dựng miền Nam (phanVienXa: true)
  // ==========================================
  {
    unitId: 4,
    soHD: '401/2026/HDKS-PVMN',
    ten: 'Khảo sát hiện trạng & Giám định chất lượng công trình Nhà máy Sika Bình Dương',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    phanVienXa: true,
    clientIdx: 9,
    giaTri: 3100,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-01',
    hanHoanThanh: '2026-06-30',
    noiDung: 'Khảo sát đo vẽ hiện trạng nứt vỡ sàn xưởng, siêu âm khuyết tật cọc nhồi và kiểm tra độ bền kiềm - sỏi.',
    hasJointVenture: false,
  },
  {
    unitId: 4,
    soHD: '402/2026/HDTN-PVMN',
    ten: 'Thí nghiệm kiểm tra chất lượng cọc nhồi D1500 bằng phương pháp khoan lõi & PIT Metro Bến Thành - Suối Tiên',
    nhomHD: 'N2B',
    capKy: 'don-vi-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    phanVienXa: true,
    clientIdx: 10,
    giaTri: 4600,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-08-15',
    hanHoanThanh: '2026-02-15',
    noiDung: 'Thí nghiệm biến dạng nhỏ PIT, siêu âm màng ống 4 kênh và thử nén mẫu lõi bê tông cọc nhồi sâu 65m.',
    hasJointVenture: false,
  },
  {
    unitId: 4,
    soHD: '403/2026/HDTV-PVMN',
    ten: 'Thẩm tra thiết kế bản vẽ thi công Trung tâm Hội nghị Quốc tế Cần Giờ TP.HCM',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    phanVienXa: true,
    clientIdx: 3,
    giaTri: 2500,
    phanTramChuTri: 78,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-10-15',
    noiDung: 'Thẩm tra an toàn kết cấu nhịp lớn vượt khẩu độ 60m vùng bão ven biển, kiểm tra sự phù hợp tiêu chuẩn kháng gió bão.',
    hasJointVenture: false,
  },
  {
    unitId: 4,
    soHD: '404/2026/HDGD-PVMN',
    ten: 'Đánh giá mức độ ăn mòn xâm thực mặn cọc bê tông cảng Cái Mép - Thị Vải',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    phanVienXa: true,
    clientIdx: 6,
    giaTri: 3900,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-20',
    hanHoanThanh: '2026-09-20',
    noiDung: 'Khảo sát lặn chụp ảnh ngầm dưới nước bề mặt cọc, đo chiều sâu thâm nhập ion Clorua và đo điện thế ăn mòn cốt thép.',
    hasJointVenture: false,
  },
  {
    unitId: 4,
    soHD: '405/2026/HDTN-PVMN',
    ten: 'Thí nghiệm nén tĩnh tải trọng 1200T cọc móng tòa nhà Landmark 81 giai đoạn duy tu',
    nhomHD: 'N2B',
    capKy: 'vien-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    phanVienXa: true,
    clientIdx: 3,
    giaTri: 5800,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-10-15',
    hanHoanThanh: '2026-04-15',
    noiDung: 'Lắp đặt hệ dầm dàn phản lực thử nén tĩnh tải trọng cực lớn 1.200 tấn, quan trắc độ lún ổn định theo thời gian.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 5: IBST.AM - Trung tâm Tư vấn chống ăn mòn và xây dựng
  // ==========================================
  {
    unitId: 5,
    soHD: '501/2026/HDTV-TTAM',
    ten: 'Tư vấn quan trắc môi trường & Thí nghiệm đo độ ồn, rung chấn dự án Cảng hàng không Long Thành GĐ1',
    nhomHD: 'N2D',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 0,
    giaTri: 2800,
    phanTramChuTri: 85,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-01',
    hanHoanThanh: '2026-10-01',
    noiDung: 'Đo đạc quan trắc chất lượng không khí, tiếng ồn liên tục 24/7 và vi khí hậu khu vực san lấp mặt bằng Cảng hàng không Long Thành.',
    hasJointVenture: false,
  },
  {
    unitId: 5,
    soHD: '502/2026/HDTC-TTAM',
    ten: 'Thi công bọc phủ composite chống ăn mòn hóa chất bồn bể Nhà máy Lọc dầu Nghi Sơn',
    nhomHD: 'N3',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 7,
    giaTri: 6200,
    phanTramChuTri: 90,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-15',
    hanHoanThanh: '2026-07-15',
    noiDung: 'Xử lý bề mặt phun hạt mài chuẩn Sa 2.5, quét sơn lót epoxy giàu kẽm và thi công 3 lớp sợi thủy tinh gia cường composite chịu axit.',
    hasJointVenture: false,
  },
  {
    unitId: 5,
    soHD: '503/2026/HDKS-TTAM',
    ten: 'Khảo sát điện thế ăn mòn cốt thép cầu vượt biển Tân Vũ - Lạch Huyện',
    nhomHD: 'N1A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 1900,
    phanTramChuTri: 78,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-15',
    noiDung: 'Đo điện thế nửa pin nửa tế bào (Half-cell potential), xác định vùng rủi ro ăn mòn ngầm bê tông dầm cầu tiếp xúc hơi muối mặn.',
    hasJointVenture: false,
  },
  {
    unitId: 5,
    soHD: '504/2026/HDTV-TTAM',
    ten: 'Tư vấn thiết kế giải pháp bảo vệ catốt bằng dòng điện cưỡng bức kè biển Quy Nhơn',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 3200,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-11-20',
    hanHoanThanh: '2026-05-20',
    noiDung: 'Tính toán thiết kế hệ thống cực anot titan MMO, tủ chỉnh lưu điều khiển tự động bảo vệ công trình chắn sóng khỏi bị gỉ sét.',
    hasJointVenture: false,
  },
  {
    unitId: 5,
    soHD: '505/2026/HDTN-TTAM',
    ten: 'Thí nghiệm gia tốc ăn mòn muối sương và kiểm tra độ bám dính lớp phủ bảo vệ silane',
    nhomHD: 'N4',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 9,
    giaTri: 1500,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-08-01',
    hanHoanThanh: '2026-02-01',
    noiDung: 'Thử nghiệm phun muối sương 1000 giờ trong buồng vi khí hậu nhân tạo theo ASTM B117 và đo lực bám dính màng sơn Pull-off test.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 6: IBST.TD - Trung tâm Tư vấn trắc địa và xây dựng
  // ==========================================
  {
    unitId: 6,
    soHD: '601/2026/HDKS-TTTD',
    ten: 'Quan trắc chuyển vị ngang & Lún tháp đôi hỗn hợp 45 tầng tại Bắc Ninh',
    nhomHD: 'N2E',
    capKy: 'don-vi-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    clientIdx: 4,
    giaTri: 1650,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2026-01-10',
    hanHoanThanh: '2026-05-30',
    noiDung: 'Lắp đặt 48 mốc chuẩn lún kim loại sâu 25m, dùng máy thủy bình điện tử Leica LS15 đo định kỳ 15 ngày/lần.',
    hasJointVenture: false,
  },
  {
    unitId: 6,
    soHD: '602/2026/HDKS-TTTD',
    ten: 'Khảo sát trắc địa địa hình tỷ lệ 1/500 bằng công nghệ bay chụp UAV LiDAR Khu đô thị Nam An Khánh',
    nhomHD: 'N2E',
    capKy: 'don-vi-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    clientIdx: 1,
    giaTri: 1350,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-08-15',
    noiDung: 'Bay chụp LiDAR độ phân giải cao trích xuất mô hình số độ cao DEM/DSM và bình đồ địa hình số khu đất 150 ha.',
    hasJointVenture: false,
  },
  {
    unitId: 6,
    soHD: '603/2026/HDTV-TTTD',
    ten: 'Thiết lập lưới khống chế trắc địa độ chính xác cao thi công cầu dây văng Rạch Miễu 2',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 2700,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-05-15',
    hanHoanThanh: '2026-10-15',
    noiDung: 'Xây dựng mạng lưới GPS tĩnh hạng II định vị tim trục tháp cầu và hệ mốc chuẩn quan trắc độ cong dầm chủ.',
    hasJointVenture: false,
  },
  {
    unitId: 6,
    soHD: '604/2026/HDKS-TTTD',
    ten: 'Quan trắc biến dạng đập thủy điện Bản Vẽ trong mùa tích nước và xả lũ',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    clientIdx: 6,
    giaTri: 3400,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-20',
    hanHoanThanh: '2026-08-20',
    noiDung: 'Quan trắc chuyển vị không gian 3 chiều thân đập bê tông trọng lực, phân tích vector chuyển vị dưới áp lực cột nước hồ chứa.',
    hasJointVenture: false,
  },
  {
    unitId: 6,
    soHD: '605/2026/HDTN-TTTD',
    ten: 'Kiểm chuẩn độ võng và độ nghiêng trục tháp phát sóng truyền hình Tam Đảo',
    nhomHD: 'N2B',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 1200,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-07-20',
    hanHoanThanh: '2026-01-20',
    noiDung: 'Đo tọa độ không gian tim thân tháp bằng máy toàn đạc điện tử độ chính xác 0.5 giây và tính toán góc nghiêng phương vị.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 7: IBST.CN - Trung tâm Phát triển công nghệ và vật liệu xây dựng
  // ==========================================
  {
    unitId: 7,
    soHD: '701/2026/HDTN-TTCN',
    ten: 'Thí nghiệm cơ lý & Độ phát thải VOC vật liệu hoàn thiện Tòa nhà Quốc hội',
    nhomHD: 'N2C',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 1800,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-30',
    noiDung: 'Thí nghiệm kiểm định hàm lượng hợp chất hữu cơ dễ bay hơi VOC, formaldehyd và độ bền mài mòn đá ốp lát tự nhiên.',
    hasJointVenture: false,
  },
  {
    unitId: 7,
    soHD: '702/2026/HDTV-TTCN',
    ten: 'Tư vấn công nghệ sản xuất gạch nhẹ AAC sử dụng tro xỉ Nhà máy Nhiệt điện Phả Lại',
    nhomHD: 'N4',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 8,
    giaTri: 2600,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-25',
    hanHoanThanh: '2026-09-25',
    noiDung: 'Chuyển giao công nghệ phối trộn tro bay, vôi và bột nhôm sản xuất gạch bê tông khí chưng áp đạt chuẩn thân thiện môi trường.',
    hasJointVenture: false,
  },
  {
    unitId: 7,
    soHD: '703/2026/HDKS-TTCN',
    ten: 'Khảo sát đánh giá độ bền vật liệu gạch cổ & Vữa vôi phục vụ trùng tu Quần thể Di tích Cố đô Huế',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 3500,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-10',
    hanHoanThanh: '2026-08-10',
    noiDung: 'Phân tích thành phần khoáng vật hóa thạch, thử nghiệm khả năng chịu thời tiết và khôi phục công thức vữa truyền thống.',
    hasJointVenture: false,
  },
  {
    unitId: 7,
    soHD: '704/2026/HDTN-TTCN',
    ten: 'Thí nghiệm chống cháy EI 120 tấm tường thạch cao chống cháy Nhà ga T3 Tân Sơn Nhất',
    nhomHD: 'N2F',
    capKy: 'don-vi-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    clientIdx: 0,
    giaTri: 2900,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-11-15',
    hanHoanThanh: '2026-05-15',
    noiDung: 'Đốt thử nghiệm mẫu kích thước thật trong lò đốt đứng theo tiêu chuẩn ISO 834, xác định giới hạn chịu lửa 120 phút.',
    hasJointVenture: false,
  },
  {
    unitId: 7,
    soHD: '705/2026/HDTV-TTCN',
    ten: 'Nghiên cứu phát triển vữa rót không co cường độ cao dùng cho bệ máy turbin gió',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 4100,
    phanTramChuTri: 78,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-06-25',
    hanHoanThanh: '2025-12-25',
    noiDung: 'Tối ưu hóa tính linh động, khả năng phát triển cường độ sớm đạt 80 MPa sau 24h chịu tải rung động cực lớn của cánh quạt gió.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 12: IBST.MT - Phân Viện KHCN Xây dựng miền Trung (phanVienXa: true)
  // ==========================================
  {
    unitId: 12,
    soHD: '1201/2026/HDKS-PVMT',
    ten: 'Thí nghiệm & Đánh giá an toàn đê biển, đập thủy lợi ứng phó sự cố bão lũ tại Thừa Thiên Huế',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    phanVienXa: true,
    clientIdx: 11,
    giaTri: 3400,
    phanTramChuTri: 78,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-07-20',
    hanHoanThanh: '2026-01-20',
    noiDung: 'Khảo sát quét Georadar xuyên đất phát hiện hốc rỗng thân đê, thí nghiệm xói mòn bề mặt kè bê tông chắn sóng.',
    hasJointVenture: false,
  },
  {
    unitId: 12,
    soHD: '1202/2026/HDTN-PVMT',
    ten: 'Thí nghiệm nén vữa & Thí nghiệm kéo thép cốt dự án Cầu vượt sông Hương Đà Nẵng',
    nhomHD: 'N2F',
    capKy: 'don-vi-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    phanVienXa: true,
    clientIdx: 14,
    giaTri: 1950,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-30',
    noiDung: 'Thí nghiệm độ bền kéo, giới hạn chảy steel bars D25-D40 và thử tải nén vữa rót không co bù.',
    hasJointVenture: false,
  },
  {
    unitId: 12,
    soHD: '1203/2026/HDGD-PVMT',
    ten: 'Giám định chất lượng kết cấu bê tông khu nghỉ dưỡng ven biển Hội An bị sóng đánh sập',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    phanVienXa: true,
    clientIdx: 3,
    giaTri: 2500,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-05-02',
    hanHoanThanh: '2026-09-02',
    noiDung: 'Kiểm định khả năng chịu lực của đài móng cọc, đánh giá mức độ suy giảm cường độ bê tông do ngâm nước biển kéo dài.',
    hasJointVenture: false,
  },
  {
    unitId: 12,
    soHD: '1204/2026/HDKS-PVMT',
    ten: 'Khảo sát địa chất thủy văn & Đo đạc dòng chảy bồi lắng Cảng Liên Chiểu GĐ1',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: 'khao-sat-dia-chat',
    phanVienXa: true,
    clientIdx: 2,
    giaTri: 4800,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-25',
    hanHoanThanh: '2026-07-25',
    noiDung: 'Đo vận tốc dòng chảy thủy triều bằng thiết bị ADCP, khoan mẫu trầm tích đáy biển và mô phỏng sa bồi luồng tàu.',
    hasJointVenture: false,
  },
  {
    unitId: 12,
    soHD: '1205/2026/HDTV-PVMT',
    ten: 'Thẩm tra thiết kế nâng cấp sân đỗ và đường lăn Sân bay Phù Cát Bình Định',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    phanVienXa: true,
    clientIdx: 0,
    giaTri: 2200,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-10-18',
    hanHoanThanh: '2026-04-18',
    noiDung: 'Thẩm tra tải trọng tác dụng của máy bay Code E, tính toán kết cấu áo đường mềm bê tông nhựa cải tiến polymer.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 13: IBST.KCT - Trung tâm Kết cấu thép và xây dựng
  // ==========================================
  {
    unitId: 13,
    soHD: '1301/2026/HDTV-TTKCT',
    ten: 'Thẩm tra thiết kế nhà xưởng kết cấu thép nhịp lớn 72m Nhà máy Nhôm Dinco',
    nhomHD: 'N2G',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 1400,
    phanTramChuTri: 85,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-03-15',
    hanHoanThanh: '2026-06-15',
    noiDung: 'Tính toán liên kết bulong cường độ cao, kiểm tra ổn định tổng thể vì kèo dàn thép và độ võng dưới tải trọng gió.',
    hasJointVenture: false,
  },
  {
    unitId: 13,
    soHD: '1302/2026/HDTN-TTKCT',
    ten: 'Thử nghiệm khả năng chịu tải liên kết bu lông tự đứt S10T dự án Sân bay Long Thành',
    nhomHD: 'N2F',
    capKy: 'don-vi-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    clientIdx: 0,
    giaTri: 2300,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-15',
    noiDung: 'Thử nghiệm mô men xiết bu lông, hệ số ma sát bề mặt tiếp xúc phun bi và kiểm tra phá hủy kéo đứt bu lông mác cao.',
    hasJointVenture: false,
  },
  {
    unitId: 13,
    soHD: '1303/2026/HDGD-TTKCT',
    ten: 'Giám định sự cố sập vì kèo vòm thép không gian Trung tâm Thể thao Đà Nẵng',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 3200,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-18',
    hanHoanThanh: '2026-07-18',
    noiDung: 'Phân tích cơ cấu phá hủy quả cầu liên kết, siêu âm khuyết tật mối hàn ống thép và kiểm toán ổn định phi tuyến kết cấu.',
    hasJointVenture: false,
  },
  {
    unitId: 13,
    soHD: '1304/2026/HDTV-TTKCT',
    ten: 'Tư vấn thiết kế tối ưu hóa kết cấu thép giàn không gian Nhà ga đường sắt cao tốc',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 4600,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-09-12',
    hanHoanThanh: '2026-03-12',
    noiDung: 'Ứng dụng thuật toán tối ưu hóa hình học tiết diện thép hộp, giảm 18% khối lượng thép kết cấu mái nhịp lớn 90m.',
    hasJointVenture: false,
  },
  {
    unitId: 13,
    soHD: '1305/2026/HDTN-TTKCT',
    ten: 'Thí nghiệm kiểm tra mối hàn siêu âm UT và chụp phim RT dầm thép cầu Bạch Đằng 2',
    nhomHD: 'N2F',
    capKy: 'don-vi-ky',
    loaiDacThu: 'tn-dat-vl-thep-han',
    clientIdx: 6,
    giaTri: 1850,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-07-15',
    hanHoanThanh: '2026-01-15',
    noiDung: 'Kiểm tra không phá hủy 100% mối hàn đối đầu dầm chữ I bằng đầu dò góc siêu âm UT và kiểm tra khuyết tật chụp X-quang RT.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 14: IBST.TKXD - Trung tâm Tư vấn thiết kế và xây dựng
  // ==========================================
  {
    unitId: 14,
    soHD: '1401/2026/HDTV-TTTK',
    ten: 'Tư vấn thiết kế bản vẽ thi công & Tổng dự toán dự án Bệnh viện đa khoa Quảng Ninh 500 giường',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 13,
    giaTri: 8900,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-09-05',
    hanHoanThanh: '2026-04-05',
    noiDung: 'Thiết kế kiến trúc, kết cấu, điện nước (MEP), phòng cháy chữa cháy (PCCC) và ứng dụng BIM LOD350 toàn bộ Bệnh viện.',
    hasJointVenture: true,
    jointVentureName: 'CTCP Tư vấn Kiến trúc Việt Nam',
    jointVenturePct: 40,
  },
  {
    unitId: 14,
    soHD: '1402/2026/HDTV-TTTK',
    ten: 'Lập quy hoạch tổng mặt bằng & Thiết kế cơ sở Ký túc xá Đại học Quốc gia Hà Nội',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 3800,
    phanTramChuTri: 78,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-10-30',
    noiDung: 'Thiết kế quy hoạch chi tiết 1/500 khu ký túc xá 12.000 sinh viên, thiết kế cơ sở hệ thống hạ tầng giao thông và thoát nước nội khu.',
    hasJointVenture: false,
  },
  {
    unitId: 14,
    soHD: '1403/2026/HDTV-TTTK',
    ten: 'Thiết kế bản vẽ thi công cải tạo & Nâng tầng Khách sạn Công đoàn Việt Nam',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 2100,
    phanTramChuTri: 85,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-05',
    hanHoanThanh: '2026-08-05',
    noiDung: 'Lập phương án cấy thêm dầm thép sàn liên hợp composite, gia cố cột tầng dưới để nâng thêm 3 tầng dịch vụ hội nghị.',
    hasJointVenture: false,
  },
  {
    unitId: 14,
    soHD: '1404/2026/HDTV-TTTK',
    ten: 'Thiết kế kỹ thuật hệ thống cơ điện MEP và điều hòa thông gió Trung tâm Dữ liệu IDC Viettel',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 5500,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-10',
    hanHoanThanh: '2026-07-10',
    noiDung: 'Thiết kế hệ thống điện dự phòng 2N, giải pháp làm mát chiller chính xác và hệ thống chữa cháy khí sạch FM200 chuẩn Uptime Tier III.',
    hasJointVenture: false,
  },
  {
    unitId: 14,
    soHD: '1405/2026/HDTV-TTTK',
    ten: 'Lập hồ sơ mời thầu & Dự toán gói thầu xây lắp Trường PTTH Chuyên Bắc Giang',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 5,
    giaTri: 1600,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-06-10',
    hanHoanThanh: '2025-12-10',
    noiDung: 'Bóc tách khối lượng chi tiết theo đơn giá định mức Bộ Xây dựng hiện hành, biên soạn hồ sơ mời thầu theo Luật Đấu thầu.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 15: IBST.CNXD - Trung tâm Công nghệ xây dựng
  // ==========================================
  {
    unitId: 15,
    soHD: '1501/2026/HDTV-TTCNXD',
    ten: 'Tư vấn biện pháp thi công cốp pha trượt tháp làm mát Nhà máy Nhiệt điện Vũng Áng 2',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 4300,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-12',
    hanHoanThanh: '2026-08-12',
    noiDung: 'Tính toán hệ kích thủy lực leo cốp pha trượt đường kính cong hyperbol, kiểm toán ổn định gió bão khi thi công ở độ cao 140m.',
    hasJointVenture: false,
  },
  {
    unitId: 15,
    soHD: '1502/2026/HDTN-TTCNXD',
    ten: 'Thử tải giàn giáo ringlock & Khả năng chịu lực hệ chống sàn siêu cao tầng',
    nhomHD: 'N2B',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 3,
    giaTri: 1700,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-08-30',
    noiDung: 'Thí nghiệm nén uốn cột giáo ringlock chịu tải cực đại 12 tấn tại hiện trường, đánh giá độ võng giằng đĩa bát.',
    hasJointVenture: false,
  },
  {
    unitId: 15,
    soHD: '1503/2026/HDGD-TTCNXD',
    ten: 'Đánh giá an toàn công nghệ thi công hầm chui Lê Văn Lương giai đoạn hoàn thiện',
    nhomHD: 'N1A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 2900,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-18',
    hanHoanThanh: '2026-09-18',
    noiDung: 'Rà soát biện pháp đào xén đường giao thông đô thị, kiểm tra an toàn hệ đà giáo đỡ giao thông tạm phía trên nóc hầm chui.',
    hasJointVenture: false,
  },
  {
    unitId: 15,
    soHD: '1504/2026/HDTV-TTCNXD',
    ten: 'Lập biện pháp hạ thủy và lắp đặt dầm chữ U cầu cạn Metro số 1 TP.HCM',
    nhomHD: 'N2G',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 10,
    giaTri: 3100,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-10-08',
    hanHoanThanh: '2026-04-08',
    noiDung: 'Thiết kế xe lao phóng dầm trọng tải 500 tấn di chuyển trên trụ cầu cạn, tính toán ổn định chống lật khi lao nhịp cong bán kính 300m.',
    hasJointVenture: false,
  },
  {
    unitId: 15,
    soHD: '1505/2026/HDTC-TTCNXD',
    ten: 'Xử lý kỹ thuật chống rung chấn móng máy ép cán thép Nhà máy Hòa Phát Dung Quất',
    nhomHD: 'N3',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 6800,
    phanTramChuTri: 90,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-06-15',
    hanHoanThanh: '2025-12-15',
    noiDung: 'Lắp đặt đệm cao su giảm chấn đàn hồi cao và thi công khối móng bê tông nặng độc lập triệt tiêu xung kích tải trọng động.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 16: IBST.CNHT - Trung tâm Tư vấn xây dựng công nghiệp và hạ tầng
  // ==========================================
  {
    unitId: 16,
    soHD: '1601/2026/HDTV-TTCNHT',
    ten: 'Tư vấn quản lý dự án & Giám sát thi công Hạ tầng KCN Đồng Văn IV Hà Nam',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 6500,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-18',
    hanHoanThanh: '2026-10-18',
    noiDung: 'Giám sát thi công san nền 100 ha, đường giao thông trục chính KCN, hệ thống mương thoát nước mưa và trạm xử lý nước thải tập trung.',
    hasJointVenture: true,
    jointVentureName: 'CTCP Tư vấn Công trình Xây dựng Hạ tầng',
    jointVenturePct: 30,
  },
  {
    unitId: 16,
    soHD: '1602/2026/HDTV-TTCNHT',
    ten: 'Thẩm tra thiết kế mạng lưới cấp thoát nước & Xử lý nước thải KĐT sinh thái Ecopark',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 3,
    giaTri: 2400,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-08-25',
    noiDung: 'Tính toán thủy lực đường ống cấp nước sạch, mô phỏng mạng lưới thoát nước mưa tránh ngập cục bộ lưu vực hồ sinh thái.',
    hasJointVenture: false,
  },
  {
    unitId: 16,
    soHD: '1603/2026/HDTV-TTCNHT',
    ten: 'Giám sát thi công xây dựng trạm biến áp 500kV Tây Hà Nội',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 3700,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-12',
    hanHoanThanh: '2026-10-12',
    noiDung: 'Giám sát ép cọc bê tông móng máy biến áp 500kV, thi công mương cáp ngầm chống thấm và hệ thống tiếp địa chống sét trạm.',
    hasJointVenture: false,
  },
  {
    unitId: 16,
    soHD: '1604/2026/HDTV-TTCNHT',
    ten: 'Tư vấn đấu thầu lựa chọn nhà thầu EPC Nhà máy xử lý rác thải phát điện Sóc Sơn',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 1900,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-11-05',
    hanHoanThanh: '2026-04-05',
    noiDung: 'Lập hồ sơ mời thầu quốc tế tiêu chuẩn FIDIC Silver Book, đánh giá hồ sơ đề xuất tài chính kỹ thuật gói thầu EPC lò đốt phát điện.',
    hasJointVenture: false,
  },
  {
    unitId: 16,
    soHD: '1605/2026/HDTV-TTCNHT',
    ten: 'Đánh giá tác động môi trường & Nghiệm thu hoàn thành tuyến cống thoát nước mưa Yên Sở',
    nhomHD: 'N4',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 2600,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-06-20',
    hanHoanThanh: '2025-12-20',
    noiDung: 'Kiểm tra chất lượng nước mặt hồ điều hòa Yên Sở sau khi thông tuyến cống hộp đôi kích thước 2x(3m x 3m).',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 17: IBST.TBXD - Trung tâm Tư vấn thiết bị và xây dựng
  // ==========================================
  {
    unitId: 17,
    soHD: '1701/2026/HDTN-TTTB',
    ten: 'Kiểm định kỹ thuật an toàn cần trục tháp & Vận thăng lồng Tổ hợp The Manor Central Park',
    nhomHD: 'N2G',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 1500,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-08-30',
    noiDung: 'Thử nghiệm tải tĩnh 125% và tải động 110% cần trục tháp Potain, kiểm tra phanh hãm rơi tự do vận thăng chở người.',
    hasJointVenture: false,
  },
  {
    unitId: 17,
    soHD: '1702/2026/HDTV-TTTB',
    ten: 'Kiểm định hệ thống phòng cháy chữa cháy PCCC và hút khói hành lang TTTM Aeon Mall Huế',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 11,
    giaTri: 3300,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-20',
    hanHoanThanh: '2026-08-20',
    noiDung: 'Đo lưu lượng áp lực vòi phun sprinkler, kiểm tra áp suất dương buồng thang thoát hiểm và tạo khói thử nghiệm van ngăn cháy.',
    hasJointVenture: false,
  },
  {
    unitId: 17,
    soHD: '1703/2026/HDTN-TTTB',
    ten: 'Thử nghiệm an toàn thang máy tốc độ cao 7m/s Tòa tháp Vietcombank Tower',
    nhomHD: 'N2B',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 3,
    giaTri: 2100,
    phanTramChuTri: 85,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-15',
    hanHoanThanh: '2026-06-15',
    noiDung: 'Đo gia tốc rung giật cabin thang máy, kiểm tra bộ khống chế vượt tốc governor và bộ đệm thủy lực hố pít.',
    hasJointVenture: false,
  },
  {
    unitId: 17,
    soHD: '1704/2026/HDTV-TTTB',
    ten: 'Tư vấn lắp đặt & Thẩm định công nghệ hệ thống lạnh Chiller trung tâm Bệnh viện K Tân Triều',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 5,
    giaTri: 2800,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-10-10',
    hanHoanThanh: '2026-03-10',
    noiDung: 'Đánh giá chỉ số hiệu suất COP dàn máy chiller biến tần ly tâm, kiểm tra độ ồn cách âm phòng máy đạt tiêu chuẩn y tế.',
    hasJointVenture: false,
  },
  {
    unitId: 17,
    soHD: '1705/2026/HDTN-TTTB',
    ten: 'Kiểm tra định kỳ van an toàn & Đường ống áp lực cao Nhà máy Nhiệt điện Thái Bình 2',
    nhomHD: 'N4',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 6,
    giaTri: 1900,
    phanTramChuTri: 78,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-06-05',
    hanHoanThanh: '2025-12-05',
    noiDung: 'Thử thủy lực áp suất cao 1.5 lần áp suất làm việc đường ống hơi chính, hiệu chỉnh áp suất xả của cụm van an toàn lò hơi.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 18: IBST.QT - Trung tâm các Dự án quốc tế và xây dựng
  // ==========================================
  {
    unitId: 18,
    soHD: '1801/2026/HDTV-TTQT',
    ten: 'Tư vấn áp dụng hệ thống tiêu chuẩn Eurocode thiết kế Cầu dây văng Đại Ngãi',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 5200,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-22',
    hanHoanThanh: '2026-08-22',
    noiDung: 'So sánh tương đương giữa Tiêu chuẩn Việt Nam và Eurocodes EN 1991/1992, lập bảng hướng dẫn quy đổi tổ hợp tải trọng gió bão.',
    hasJointVenture: true,
    jointVentureName: 'Tập đoàn Tư vấn Quốc tế Nippon Koei',
    jointVenturePct: 35,
  },
  {
    unitId: 18,
    soHD: '1802/2026/HDTV-TTQT',
    ten: 'Biên soạn Sổ tay hướng dẫn thực hành ACI 318 cho các công trình cao tầng',
    nhomHD: 'N4',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 1200,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-30',
    noiDung: 'Biên dịch, đối chiếu phụ lục quốc gia và xây dựng ví dụ tính toán cốt thép vách kháng chấn theo chuẩn Viện Bê tông Hoa Kỳ ACI.',
    hasJointVenture: false,
  },
  {
    unitId: 18,
    soHD: '1803/2026/HDTV-TTQT',
    ten: 'Hợp tác nghiên cứu với Viện CABR Trung Quốc về công nghệ kết cấu bê tông đúc sẵn siêu cao',
    nhomHD: 'N4',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 7,
    giaTri: 3600,
    phanTramChuTri: 78,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-10',
    hanHoanThanh: '2026-11-10',
    noiDung: 'Nghiên cứu ứng dụng công nghệ mối nối ống gối grouted sleeve cho cột bê tông đúc sẵn nhà siêu cao tầng chịu động đất.',
    hasJointVenture: false,
  },
  {
    unitId: 18,
    soHD: '1804/2026/HDTV-TTQT',
    ten: 'Tư vấn kỹ thuật giám sát độc lập dự án ODA Nhật Bản xử lý nước thải Yên Xá',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 4,
    giaTri: 4700,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-08-20',
    hanHoanThanh: '2026-03-20',
    noiDung: 'Giám sát kỹ thuật công nghệ khoan kích ngầm pipe jacking qua lòng sông Tô Lịch, kiểm tra an toàn chuyển vị mặt đường.',
    hasJointVenture: false,
  },
  {
    unitId: 18,
    soHD: '1805/2026/HDTV-TTQT',
    ten: 'Đánh giá rủi ro kết cấu theo tiêu chuẩn quốc tế ASTM cho Nhà máy Lego Bình Dương',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 9,
    giaTri: 2900,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-06-01',
    hanHoanThanh: '2025-12-01',
    noiDung: 'Đánh giá an toàn chống lốc xoáy và độ kín khít lớp vỏ bao che đạt chứng chỉ công trình xanh LEED Gold của Hoa Kỳ.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 19: IBST.BIM - Trung tâm Tư vấn và Ứng dụng BIM trong xây dựng
  // ==========================================
  {
    unitId: 19,
    soHD: '1901/2026/HDTV-TTBIM',
    ten: 'Tư vấn xây dựng Kế hoạch thực hiện BIM (BEP) & Mô hình BIM 3D LOD 350 Sân bay Chu Lai',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 0,
    giaTri: 2500,
    phanTramChuTri: 85,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-30',
    noiDung: 'Xây dựng tài liệu BEP theo Quyết định 258/QĐ-BXD, dựng mô hình 3D kết cấu - kiến trúc - cơ điện phục vụ quản lý dự án.',
    hasJointVenture: false,
  },
  {
    unitId: 19,
    soHD: '1902/2026/HDTV-TTBIM',
    ten: 'Kiểm tra xung đột Clash Detection đa bộ môn kiến trúc - kết cấu - MEP Bệnh viện Nhi TW GĐ2',
    nhomHD: 'N2A',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 5,
    giaTri: 1800,
    phanTramChuTri: 85,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-15',
    hanHoanThanh: '2026-07-15',
    noiDung: 'Sử dụng Autodesk Navisworks xuất báo cáo phát hiện và xử lý hơn 1.200 điểm giao cắt giữa đường ống kỹ thuật và dầm sàn.',
    hasJointVenture: false,
  },
  {
    unitId: 19,
    soHD: '1903/2026/HDTV-TTBIM',
    ten: 'Lập mô hình BIM 4D mô phỏng tiến độ thi công hố đào sâu Khách sạn Hilton Hải Phòng',
    nhomHD: 'N1B',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 3,
    giaTri: 3400,
    phanTramChuTri: 78,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-02-01',
    hanHoanThanh: '2026-08-01',
    noiDung: 'Gắn dữ liệu tiến độ MS Project vào mô hình 3D, mô phỏng video trình tự thi công đào đất, đổ bê tông giằng chống sàn tầng hầm.',
    hasJointVenture: false,
  },
  {
    unitId: 19,
    soHD: '1904/2026/HDTV-TTBIM',
    ten: 'Mô hình hóa BIM hoàn công As-built LOD 500 phục vụ vận hành quản lý tài sản Tòa nhà EVN',
    nhomHD: 'N2A',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 4200,
    phanTramChuTri: 78,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-09-15',
    hanHoanThanh: '2026-03-15',
    noiDung: 'Gắn thông số bảo trì, lý lịch thiết bị điện tử COBie vào mô hình 3D hoàn công, kết nối với phần mềm quản lý tòa nhà BMS.',
    hasJointVenture: false,
  },
  {
    unitId: 19,
    soHD: '1905/2026/HDTV-TTBIM',
    ten: 'Đào tạo chuyển giao công nghệ BIM cho cán bộ quản lý dự án Ban QLDA Giao thông Hà Nội',
    nhomHD: 'N4',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 1400,
    phanTramChuTri: 85,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-07-01',
    hanHoanThanh: '2025-12-01',
    noiDung: 'Tổ chức khóa đào tạo 60 tiết về kiểm tra mô hình BIM trên môi trường dữ liệu chung CDE và nghiệm thu bàn giao hồ sơ số.',
    hasJointVenture: false,
  },

  // ==========================================
  // ĐƠN VỊ 20: IBST.CTCP - Công ty CP Đầu tư và Công nghệ xây dựng IBST
  // ==========================================
  {
    unitId: 20,
    soHD: '2001/2026/HDTC-CTCP',
    ten: 'Thi công xử lý chống thấm ngược tầng hầm sâu 3 tầng Tổ hợp Vincom Plaza Hải Phòng',
    nhomHD: 'N3',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 3,
    giaTri: 7800,
    phanTramChuTri: 90,
    buocHienTai: 'dang-thuc-hien',
    trangThai: 'dang-thuc-hien',
    ngayKy: '2026-01-20',
    hanHoanThanh: '2026-07-20',
    noiDung: 'Khoan cấy kim bơm keo Polyurethane trương nở chặn dòng rò rỉ, quét 2 lớp thẩm thấu tinh thể gốc xi măng màng chống thấm mặt trong vách hầm.',
    hasJointVenture: false,
  },
  {
    unitId: 20,
    soHD: '2002/2026/HDTC-CTCP',
    ten: 'Cung cấp và thi công bơm vữa không co SikaGrout cho móng turbine gió Trà Vinh',
    nhomHD: 'N3',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 7,
    giaTri: 4500,
    phanTramChuTri: 90,
    buocHienTai: 'du-thao',
    trangThai: 'du-thao',
    ngayKy: null,
    hanHoanThanh: '2026-09-15',
    noiDung: 'Cung cấp 120 tấn vữa rót gốc xi măng chịu mỏi mác M80, thi công bơm liên tục bệ neo bulong turbine gió ven biển.',
    hasJointVenture: false,
  },
  {
    unitId: 20,
    soHD: '2003/2026/HDTC-CTCP',
    ten: 'Thi công gia cường dầm sàn bằng sợi carbon CFRP Nhà máy Điện tử Foxconn Bắc Giang',
    nhomHD: 'N3',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 3200,
    phanTramChuTri: 90,
    buocHienTai: 'cho-duyet',
    trangThai: 'cho-duyet',
    ngayKy: '2026-04-12',
    hanHoanThanh: '2026-07-12',
    noiDung: 'Mài phẳng bề mặt bê tông, dán 2 lớp vải sợi carbon cường độ cao tăng tải trọng sàn đặt dây chuyền máy móc SMT tự động.',
    hasJointVenture: false,
  },
  {
    unitId: 20,
    soHD: '2004/2026/HDTC-CTCP',
    ten: 'Sản xuất & Cung ứng tấm ốp bê tông tính năng cao GFRC mặt dựng Tòa nhà FPT Cần Thơ',
    nhomHD: 'N2C',
    capKy: 'don-vi-ky',
    loaiDacThu: null,
    clientIdx: 1,
    giaTri: 5100,
    phanTramChuTri: 85,
    buocHienTai: 'hoan-thanh',
    trangThai: 'hoan-thanh',
    ngayKy: '2025-09-10',
    hanHoanThanh: '2026-03-10',
    noiDung: 'Đúc sẵn 1.800 m2 tấm ốp bê tông cốt sợi thủy tinh GFRC bề mặt hoa văn 3D uốn lượn, vận chuyển và lắp dựng hoàn thiện.',
    hasJointVenture: false,
  },
  {
    unitId: 20,
    soHD: '2005/2026/HDTC-CTCP',
    ten: 'Xử lý nứt rò rỉ nước hầm đường bộ Hải Vân bằng công nghệ keo epoxy áp lực cao',
    nhomHD: 'N3',
    capKy: 'vien-ky',
    loaiDacThu: null,
    clientIdx: 2,
    giaTri: 8600,
    phanTramChuTri: 90,
    buocHienTai: 'thanh-ly',
    trangThai: 'thanh-ly',
    ngayKy: '2025-05-15',
    hanHoanThanh: '2025-11-15',
    noiDung: 'Xử lý dứt điểm các vết nứt thấm nước ngầm vòm hầm, bơm keo epoxy độ nhớt cực thấp hàn gắn kết cấu bê tông.',
    hasJointVenture: true,
    jointVentureName: 'CTCP Hạ tầng Giao thông Đèo Cả',
    jointVenturePct: 35,
  }
];

module.exports = { contractsData };
